import { createServerFn } from '@tanstack/react-start';
import { getRequest } from '@tanstack/react-start/server';
import { requireSupabaseAuth } from '@/integrations/supabase/auth-middleware';
import { z } from 'zod';
import { itemSchema } from './memory-schema';
import type { Item } from './nanti-types';
const authed=[requireSupabaseAuth] as const;
export const loadWorkspace=createServerFn({method:'GET'}).middleware(authed).handler(async({context})=>{
 const {adminDb,entitlement}=await import('./launch.server');const db=adminDb();const userId=context.userId;
 const results=await Promise.all(['tasks','waiting_items','inbox_items','people','projects','launch_settings'].map(table=>db.from(table).select('*').eq('user_id',userId)));
 for(const r of results)if(r.error)throw new Error('We could not load your memories. Please retry. / Memori belum dapat dimuat. Coba lagi.');
 const [tasks=[],waiting=[],inbox=[],people=[],projects=[],prefs=[]]=results.map(r=>r.data||[]);
 const legacy=(r:Record<string,any>,kind?:string):Item=>({...r['memory_snapshot'],id:r['id'],title:r['memory_snapshot']?.title||r['title'],kind:r['memory_snapshot']?.kind||kind||r['type'],status:r['memory_snapshot']?.status||(kind==='waiting'?(r['status']==='received'?'received':'open'):kind==='inbox'?(r['status']==='ignored'?'ignored':'inbox'):r['status']==='completed'?'done':r['status']==='dismissed'?'ignored':'open'),priority:r['memory_snapshot']?.priority||r['priority']||'medium',due:r['memory_snapshot']?.due||r['due_date']?.slice(0,10),since:r['memory_snapshot']?.since||r['started_at']?.slice(0,10),personId:r['memory_snapshot']?.personId||r['person_id']||undefined,personName:r['memory_snapshot']?.personName||r['person_name']||undefined,projectId:r['memory_snapshot']?.projectId||r['project_id']||undefined,projectName:r['memory_snapshot']?.projectName||r['project_name']||undefined,source:r['memory_snapshot']?.source||r['source']||'',quote:r['memory_snapshot']?.quote||r['quote']||r['conversation_text']||'',aiNote:r['memory_snapshot']?.aiNote||r['ai_note']||'',confidence:r['memory_snapshot']?.confidence||r['confidence']||0.7,createdBy:r['memory_snapshot']?.createdBy||'ai',createdAt:r['created_at']});
 return {items:[...tasks.map(r=>legacy(r)),...waiting.map(r=>legacy(r,'waiting')),...inbox.filter(r=>r.status!=='tracked').map(r=>({...legacy(r,'inbox'),kind:r.type||'commitment'}))],people:people.map(r=>({id:r.id,name:r.name,org:r.company||'',lastConversation:r.last_conversation_at?.slice(0,10)||'',activity:[]})),projects:projects.map(r=>({id:r.id,name:r.name,description:r.description||'',sources:[]})),settings:prefs[0]?.preferences||{},subscription:await entitlement(userId)};
});
export const saveMemories=createServerFn({method:'POST'}).middleware(authed).inputValidator((data:unknown)=>z.object({items:z.array(itemSchema).min(1).max(30)}).parse(data)).handler(async({data,context})=>{
 const {adminDb,requireAccess,limit}=await import('./launch.server');await requireAccess(context.userId);await limit(`save:${context.userId}`,120);const db=adminDb();
 // One SQL insert/upsert: retries with the same UUID cannot create duplicate rows.
 const rows=data.items.map(i=>({id:i.id,user_id:context.userId,title:i.title,type:i.kind,status:i.status==='inbox'?'review':i.status==='done'?'completed':i.status==='ignored'?'dismissed':'pending',priority:i.priority,due_date:i.due?`${i.due}T${i.time||'09:00'}:00+07:00`:null,source:i.source,memory_snapshot:{...i,createdAt:new Date().toISOString(),reminderChannels:i.reminderEnabled?['in_app']:[]},reminder_enabled:!!i.reminderEnabled,reminder_channels:i.reminderEnabled?['in_app']:[]}));
 // Never overwrite another user's UUID, even via service credentials.
 const {data:existing,error:lookupError}=await db.from('tasks').select('id,user_id').in('id',rows.map(r=>r.id));if(lookupError)throw lookupError;if(existing?.some(r=>r.user_id!==context.userId))throw new Error('Invalid memory identifier.');
 const {error}=await db.from('tasks').upsert(rows,{onConflict:'id',ignoreDuplicates:true});if(error)throw new Error('Not saved. Please retry. / Belum tersimpan. Silakan coba lagi.');const {data:saved,error:readError}=await db.from('tasks').select('memory_snapshot').eq('user_id',context.userId).in('id',rows.map(r=>r.id));if(readError||saved?.length!==rows.length)throw new Error('Some memories were not saved. Please retry.');return saved.map(r=>r.memory_snapshot as Item);
});
export const changeMemory=createServerFn({method:'POST'}).middleware(authed).inputValidator((data:unknown)=>z.object({item:itemSchema}).parse(data)).handler(async({data,context})=>{
 const {adminDb}=await import('./launch.server');const db=adminDb();const i=data.item;
 for(const table of ['tasks','waiting_items','inbox_items']){const {data:found,error}=await db.from(table).select('id').eq('id',i.id).eq('user_id',context.userId).maybeSingle();if(error)throw error;if(!found)continue;
 const status=table==='tasks'?(i.status==='done'||i.status==='received'?'completed':i.status==='ignored'?'dismissed':i.status==='inbox'?'review':'pending'):table==='waiting_items'?(i.status==='received'||i.status==='done'?'received':'waiting'):(i.status==='ignored'?'ignored':'pending');
 const patch:Record<string,unknown>={title:i.title,status,memory_snapshot:i,updated_at:new Date().toISOString()};if(table==='tasks'){patch['due_date']=i.due?`${i.due}T${i.time||'09:00'}:00+07:00`:null;patch['reminder_enabled']=!!i.reminderEnabled;patch['reminder_channels']=i.reminderEnabled?['in_app']:[];}
 const result=await db.from(table).update(patch).eq('id',i.id).eq('user_id',context.userId);if(result.error)throw new Error('Could not save the change. / Perubahan belum tersimpan.');return i;}throw new Error('Memory not found.');
});
export const deleteMemory=createServerFn({method:'POST'}).middleware(authed).inputValidator((data:unknown)=>z.object({id:z.string().uuid()}).parse(data)).handler(async({data,context})=>{const {adminDb}=await import('./launch.server');for(const table of ['tasks','waiting_items','inbox_items']){const {error}=await adminDb().from(table).delete().eq('id',data.id).eq('user_id',context.userId);if(error)throw error;}});
export const savePreferences=createServerFn({method:'POST'}).middleware(authed).inputValidator((data:unknown)=>z.object({preferences:z.record(z.unknown()).refine(x=>JSON.stringify(x).length<12000)}).parse(data)).handler(async({data,context})=>{const {adminDb}=await import('./launch.server');const {error}=await adminDb().from('launch_settings').upsert({user_id:context.userId,preferences:data.preferences});if(error)throw new Error('Preferences not saved.');});
export const getSubscription=createServerFn({method:'GET'}).middleware(authed).handler(async({context})=>{const {entitlement}=await import('./launch.server');return {...await entitlement(context.userId),paymentsEnabled:process.env['NANTI_PAYMENTS_ENABLED']==='true'&&!!process.env['MIDTRANS_SERVER_KEY']};});
export const startCheckout=createServerFn({method:'POST'}).middleware(authed).handler(async({context})=>{const {checkout}=await import('./launch.server');return checkout(context.userId,String(context.claims.email||''));});
export const submitContact=createServerFn({method:'POST'}).inputValidator((data:unknown)=>z.object({name:z.string().trim().min(1).max(120),email:z.string().email().max(254),company:z.string().max(160).optional(),message:z.string().trim().min(10).max(3000),website:z.string().max(100).optional()}).parse(data)).handler(async({data})=>{if(data.website)throw new Error('Invalid request');const {adminDb,limit}=await import('./launch.server');const {createHash}=await import('node:crypto');const request=getRequest();const ip=request.headers.get('x-vercel-forwarded-for')||request.headers.get('x-real-ip')||'unknown';await limit(`contact-ip:${createHash('sha256').update(ip).digest('hex')}`,5,3600);await limit(`contact:${createHash('sha256').update(data.email.toLowerCase()).digest('hex')}`,3,3600);const {website,...row}=data;const {error}=await adminDb().from('contact_requests').insert(row);if(error)throw new Error('Message not saved.');return {ok:true};});
export const exportAccount=createServerFn({method:'GET'}).middleware(authed).handler(async({context})=>{const {adminDb}=await import('./launch.server');const db=adminDb();const tables=['tasks','waiting_items','inbox_items','conversations','people','projects','ai_messages','launch_settings','launch_subscriptions','launch_orders'];const out:Record<string,any>={exportedAt:new Date().toISOString()};for(const table of tables){let rows:any[]=[];for(let from=0;;from+=500){const {data,error}=await db.from(table).select('*').eq('user_id',context.userId).range(from,from+499);if(error)throw error;rows=rows.concat(data||[]);if(!data||data.length<500)break;}out[table]=rows;}return out;});
export const deleteAccount=createServerFn({method:'POST'}).middleware(authed).inputValidator((data:unknown)=>z.object({confirmation:z.literal('DELETE')}).parse(data)).handler(async({context})=>{const {adminDb}=await import('./launch.server');const {error}=await adminDb().auth.admin.deleteUser(context.userId);if(error)throw new Error('Account could not be deleted. Please contact support.');return {ok:true};});
