import type { Item, Message, Person, Project } from "./nanti-types";
import { addDays, todayISO } from "./nanti-utils";

/** Calendar day n days from the real current day, in Asia/Jakarta. */
export function dayOffset(n: number): string {
  return addDays(todayISO(), n);
}

export function demoPeople(): Person[] {
  return [
    {
      id: "p-budi",
      name: "Budi Santoso",
      org: "PT ABC Export",
      role: "Purchasing Manager",
      lastConversation: dayOffset(-1),
      activity: [
        { date: dayOffset(-1), text: "Budi minta revisi pricing untuk order 500 pcs." },
        { date: dayOffset(-2), text: "Anda berjanji mengirim katalog terbaru." },
        { date: dayOffset(-4), text: "Quotation awal dikirim." },
      ],
    },
    {
      id: "p-siska",
      name: "Siska Amelia",
      org: "Marketing Team",
      role: "Graphic Designer",
      lastConversation: dayOffset(-1),
      activity: [
        { date: dayOffset(-1), text: "Siska bilang final artwork menyusul sore ini." },
        { date: dayOffset(-3), text: "Brief kampanye Ramadhan disepakati." },
      ],
    },
    {
      id: "p-hendra",
      name: "Pak Hendra",
      org: "Factory Operations",
      role: "Kepala Produksi",
      lastConversation: dayOffset(0),
      activity: [
        { date: dayOffset(0), text: "Laporan mesin 2 sedang maintenance, produksi mundur." },
        { date: dayOffset(-2), text: "Update progress 60% untuk order ABC." },
      ],
    },
    {
      id: "p-supplier",
      name: "Mr. Chen",
      org: "Supplier China",
      role: "Sales",
      lastConversation: dayOffset(-2),
      activity: [
        { date: dayOffset(-2), text: "Belum ada konfirmasi jadwal shipping." },
        { date: dayOffset(-5), text: "PO diterima dan diproses." },
      ],
    },
    {
      id: "p-dewi",
      name: "Ibu Dewi",
      org: "Bali Villa Project",
      role: "Owner",
      lastConversation: dayOffset(-1),
      activity: [
        { date: dayOffset(-1), text: "Menunggu approval budget tambahan kolam renang." },
        { date: dayOffset(-3), text: "Diskusi desain fasad villa." },
      ],
    },
    {
      id: "p-agus",
      name: "Agus Wijaya",
      org: "Management",
      role: "Direktur",
      lastConversation: dayOffset(0),
      activity: [{ date: dayOffset(0), text: "Minta rekap penjualan minggu ini sebelum Jumat." }],
    },
  ];
}

export function demoProjects(): Project[] {
  return [
    {
      id: "pr-abc",
      name: "ABC Export Order",
      description: "Order 500 pcs untuk PT ABC, termasuk quotation, katalog dan produksi.",
      sources: ["Client ABC", "Factory Operations", "Supplier"],
    },
    {
      id: "pr-villa",
      name: "Bali Villa Project",
      description: "Pembangunan villa 3 unit di Canggu, koordinasi kontraktor dan owner.",
      sources: ["Bali Villa Project", "Vendors"],
    },
    {
      id: "pr-marketing",
      name: "Marketing Campaign",
      description: "Kampanye Ramadhan: artwork, konten dan jadwal posting.",
      sources: ["Marketing Team"],
    },
    {
      id: "pr-ops",
      name: "Factory Operations",
      description: "Operasional pabrik harian dan laporan produksi.",
      sources: ["Factory Operations", "Management"],
    },
  ];
}

export function demoMessages(): Message[] {
  return [
    {
      id: "m1",
      source: "Client ABC",
      sender: "Budi Santoso",
      text: "Pak Rizky, untuk order ABC yang 500 pcs itu mereka minta update price hari ini ya.",
      at: dayOffset(0),
    },
    {
      id: "m2",
      source: "Client ABC",
      sender: "Rizky",
      text: "Besok saya kirim revisi quotation-nya Pak.",
      at: dayOffset(-1),
    },
    {
      id: "m3",
      source: "Client ABC",
      sender: "Budi Santoso",
      text: "Oke ditunggu ya Pak, owner kami butuh untuk rapat.",
      at: dayOffset(-1),
    },
    {
      id: "m4",
      source: "Supplier",
      sender: "Rizky",
      text: "Saya masih tunggu konfirmasi shipping dari supplier.",
      at: dayOffset(-2),
    },
    {
      id: "m5",
      source: "Factory Operations",
      sender: "Pak Hendra",
      text: "Mesin 2 maintenance, produksi kemungkinan mundur 2 hari.",
      at: dayOffset(0),
    },
    {
      id: "m6",
      source: "Marketing Team",
      sender: "Siska Amelia",
      text: "Final artwork saya kirim nanti sore ya Pak.",
      at: dayOffset(-1),
    },
    {
      id: "m7",
      source: "Management",
      sender: "Agus Wijaya",
      text: "Rekap penjualan harus selesai Jumat ya.",
      at: dayOffset(0),
    },
    {
      id: "m8",
      source: "Bali Villa Project",
      sender: "Ibu Dewi",
      text: "Kalau sudah ada kabar dari kontraktor kabarin saya ya.",
      at: dayOffset(-1),
    },
  ];
}

export function demoItems(): Item[] {
  return [
    {
      id: "i1",
      title: "Kirim revisi quotation",
      description: "Revisi harga untuk order 500 pcs PT ABC.",
      kind: "commitment",
      status: "open",
      priority: "high",
      due: dayOffset(-1),
      personId: "p-budi",
      projectId: "pr-abc",
      source: "Client ABC",
      quote: "Besok saya kirim revisi quotation-nya Pak.",
      aiNote: "Rizky berjanji mengirim revisi quotation keesokan harinya.",
      confidence: 0.94,
      createdBy: "ai",
    },
    {
      id: "i2",
      title: "Follow up supplier soal shipping",
      description: "Belum ada konfirmasi jadwal kapal dari Supplier China.",
      kind: "followup",
      status: "open",
      priority: "high",
      due: dayOffset(-2),
      personId: "p-supplier",
      projectId: "pr-abc",
      source: "Supplier",
      quote: "Saya masih tunggu konfirmasi shipping dari supplier.",
      aiNote: "Tidak ada balasan dari supplier selama 2 hari.",
      confidence: 0.88,
      createdBy: "ai",
    },
    {
      id: "i3",
      title: "Kirim katalog revisi",
      kind: "commitment",
      status: "open",
      priority: "high",
      due: dayOffset(0),
      time: "10:00",
      personId: "p-budi",
      projectId: "pr-abc",
      source: "Client ABC",
      quote: "Katalog terbaru saya kirim besok pagi ya Pak.",
      aiNote: "Komitmen mengirim katalog pagi ini.",
      confidence: 0.91,
      createdBy: "ai",
    },
    {
      id: "i4",
      title: "Cek update produksi",
      kind: "task",
      status: "open",
      priority: "medium",
      due: dayOffset(0),
      time: "12:00",
      personId: "p-hendra",
      projectId: "pr-ops",
      source: "Factory Operations",
      quote: "Mesin 2 maintenance, produksi kemungkinan mundur 2 hari.",
      aiNote: "Perlu konfirmasi dampak keterlambatan ke order ABC.",
      confidence: 0.79,
      createdBy: "ai",
    },
    {
      id: "i5",
      title: "Approve artwork kampanye",
      kind: "task",
      status: "open",
      priority: "medium",
      due: dayOffset(0),
      time: "16:00",
      personId: "p-siska",
      projectId: "pr-marketing",
      source: "Marketing Team",
      quote: "Final artwork saya kirim nanti sore ya Pak.",
      aiNote: "Artwork perlu approval Anda hari ini.",
      confidence: 0.83,
      createdBy: "ai",
    },
    {
      id: "i6",
      title: "Rekap penjualan mingguan",
      kind: "deadline",
      status: "open",
      priority: "high",
      due: dayOffset(2),
      personId: "p-agus",
      projectId: "pr-ops",
      source: "Management",
      quote: "Rekap penjualan harus selesai Jumat ya.",
      aiNote: "Deadline dari Direktur untuk hari Jumat.",
      confidence: 0.96,
      createdBy: "ai",
    },
    {
      id: "i7",
      title: "Cek foto progres villa",
      kind: "task",
      status: "open",
      priority: "low",
      due: dayOffset(1),
      personId: "p-dewi",
      projectId: "pr-villa",
      source: "Bali Villa Project",
      quote: "Foto progres minggu ini sudah saya upload di grup.",
      aiNote: "Perlu review foto progres sebelum laporan ke owner.",
      confidence: 0.72,
      createdBy: "ai",
    },
    // waiting
    {
      id: "w1",
      title: "Approval quotation",
      kind: "waiting",
      status: "open",
      priority: "high",
      since: dayOffset(-3),
      personId: "p-budi",
      projectId: "pr-abc",
      source: "Client ABC",
      quote: "Saya tunggu approval dari owner dulu ya Pak.",
      aiNote: "Budi belum memberi kabar approval selama 3 hari.",
      confidence: 0.9,
      createdBy: "ai",
    },
    {
      id: "w2",
      title: "Konfirmasi shipping",
      kind: "waiting",
      status: "open",
      priority: "high",
      since: dayOffset(-2),
      personId: "p-supplier",
      projectId: "pr-abc",
      source: "Supplier",
      quote: "Shipping schedule will confirm soon.",
      aiNote: "Supplier belum konfirmasi jadwal kapal.",
      confidence: 0.86,
      createdBy: "ai",
    },
    {
      id: "w3",
      title: "Final artwork",
      kind: "waiting",
      status: "open",
      priority: "medium",
      since: dayOffset(-1),
      personId: "p-siska",
      projectId: "pr-marketing",
      source: "Marketing Team",
      quote: "Final artwork saya kirim nanti sore ya Pak.",
      aiNote: "Siska berjanji mengirim artwork final.",
      confidence: 0.82,
      createdBy: "ai",
    },
    {
      id: "w4",
      title: "Approval budget kolam renang",
      kind: "waiting",
      status: "open",
      priority: "medium",
      since: dayOffset(-6),
      personId: "p-dewi",
      projectId: "pr-villa",
      source: "Bali Villa Project",
      quote: "Nanti saya diskusikan dulu dengan suami ya.",
      aiNote: "Sudah 6 hari tanpa keputusan. Waktu tunggu tidak normal.",
      confidence: 0.77,
      createdBy: "ai",
    },
    {
      id: "w5",
      title: "Laporan hasil QC batch 3",
      kind: "waiting",
      status: "open",
      priority: "low",
      since: dayOffset(-2),
      personId: "p-hendra",
      projectId: "pr-ops",
      source: "Factory Operations",
      quote: "Nanti QC saya kirim laporannya.",
      aiNote: "Laporan QC belum masuk.",
      confidence: 0.7,
      createdBy: "ai",
    },
    // inbox (detected, not tracked yet)
    {
      id: "n1",
      title: "Kirim katalog revisi ke Budi",
      kind: "commitment",
      status: "inbox",
      priority: "high",
      due: dayOffset(1),
      personId: "p-budi",
      projectId: "pr-abc",
      source: "Client ABC",
      quote: "Besok saya kirim revisinya ya Pak.",
      aiNote: "Rizky berkomitmen mengirim revisi katalog besok.",
      confidence: 0.93,
      createdBy: "ai",
    },
    {
      id: "n2",
      title: "Update pricing untuk ABC",
      kind: "task",
      status: "inbox",
      priority: "high",
      due: dayOffset(0),
      personId: "p-budi",
      projectId: "pr-abc",
      source: "Client ABC",
      quote: "Pak Rizky, untuk order ABC yang 500 pcs itu mereka minta update price hari ini ya.",
      aiNote: "Permintaan langsung dari klien dengan tenggat hari ini.",
      confidence: 0.95,
      createdBy: "ai",
    },
    {
      id: "n3",
      title: "Rekap penjualan selesai Jumat",
      kind: "deadline",
      status: "inbox",
      priority: "high",
      due: dayOffset(2),
      personId: "p-agus",
      projectId: "pr-ops",
      source: "Management",
      quote: "Harus selesai Jumat.",
      aiNote: "Deadline eksplisit disebut di grup Management.",
      confidence: 0.9,
      createdBy: "ai",
    },
    {
      id: "n4",
      title: "Follow up kontraktor villa",
      kind: "followup",
      status: "inbox",
      priority: "medium",
      due: dayOffset(1),
      personId: "p-dewi",
      projectId: "pr-villa",
      source: "Bali Villa Project",
      quote: "Kalau sudah ada kabar dari kontraktor kabarin saya ya.",
      aiNote: "Ibu Dewi meminta kabar lanjutan dari kontraktor.",
      confidence: 0.84,
      createdBy: "ai",
    },
    {
      id: "n5",
      title: "Menunggu approval owner",
      kind: "waiting",
      status: "inbox",
      priority: "medium",
      since: dayOffset(0),
      personId: "p-budi",
      projectId: "pr-abc",
      source: "Client ABC",
      quote: "Saya masih tunggu approval dari owner.",
      aiNote: "Item menunggu, bukan tugas Anda.",
      confidence: 0.88,
      createdBy: "ai",
    },
    {
      id: "n6",
      title: "Cek stok bahan baku",
      kind: "task",
      status: "inbox",
      priority: "medium",
      due: dayOffset(1),
      personId: "p-hendra",
      projectId: "pr-ops",
      source: "Factory Operations",
      quote: "Tolong cek stok besok ya.",
      aiNote: "Permintaan tugas untuk besok.",
      confidence: 0.87,
      createdBy: "ai",
    },
  ];
}
