import { createFileRoute, Link } from '@tanstack/react-router';
import { useState, type FormEvent } from 'react';
import { FileText, ImagePlus, Loader2, Check, ArrowRight, X } from 'lucide-react';
import { toast } from 'sonner';
import { PageHeader } from '@/components/nanti/app-shell';
import { useNanti } from '@/lib/nanti-store';
import { useLocale } from '@/lib/locale';
import { analyzeConversation, analyzeScreenshot } from '@/lib/nanti-ai.functions';
import type { ExtractResult, ExtractedItem } from '@/lib/nanti-ai.server';
import type { Item } from '@/lib/nanti-types';
export const Route=createFileRoute('/app/import')({head:()=>({meta:[{title:'Add a memory · NANTI'}]}),component:ImportPage});
type Draft=ExtractedItem&{id:string;selected:boolean;reminder:boolean};
function ImportPage(){const {t,locale}=useLocale();const {addItems,settings}=useNanti();const [mode,setMode]=useState<'text'|'image'>('text');const [text,setText]=useState(''),[image,setImage]=useState(''),[source,setSource]=useState(''),[me,setMe]=useState(settings.preferredName||settings.name),[date,setDate]=useState(''),[timezone,setTimezone]=useState<'Asia/Jakarta'|'Asia/Makassar'|'Asia/Jayapura'>('Asia/Jakarta');const [result,setResult]=useState<ExtractResult|null>(null),[drafts,setDrafts]=useState<Draft[]>([]),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[savedCount,setSavedCount]=useState(0);
 const patch=(id:string,values:Partial<Draft>)=>setDrafts(s=>s.map(i=>i.id===id?{...i,...values}:i));
 async function analyze(e:FormEvent){e.preventDefault();setBusy(true);setError('');setResult(null);setDrafts([]);setSavedCount(0);try{const context={source,me,conversationDate:date||undefined,timezone,language:locale};const r=mode==='text'?await analyzeConversation({data:{text,...context}}):await analyzeScreenshot({data:{image,...context}});setResult(r);setDrafts(r.items.map(i=>({...i,id:crypto.randomUUID(),selected:true,reminder:false})));}catch(e){setError(e instanceof Error?e.message:t('Could not read this conversation. Please retry.','Percakapan belum dapat dibaca. Silakan coba lagi.'));}finally{setBusy(false);}}
 async function save(){const chosen=drafts.filter(i=>i.selected);if(chosen.some(i=>i.owner==='unknown'||!i.title.trim())){setError(t('Please confirm who will act on each selected memory.','Pastikan siapa yang bertindak pada setiap memori pilihan.'));return;}setSaving(true);setError('');try{const items:Item[]=chosen.map(i=>({id:i.id,title:i.title.trim(),kind:i.owner==='other'?'waiting':i.kind==='waiting'?'commitment':i.kind,status:'open',priority:i.priority,due:i.whenParsed||undefined,time:i.dueTime,personName:i.person||i.who||undefined,projectName:i.project||undefined,source:source||t('Added conversation','Percakapan tambahan'),sourceType:mode==='text'?'paste':'screenshot',quote:i.quote,aiNote:i.aiNote,confidence:i.confidence,createdBy:'ai',createdAt:new Date().toISOString(),since:i.owner==='other'?(date||undefined):undefined,reminderEnabled:i.reminder&&!!i.whenParsed,reminderChannels:i.reminder&&i.whenParsed?['in_app']:[]}));await addItems(items);setDrafts(s=>s.filter(i=>!chosen.some(c=>c.id===i.id)));setSavedCount(n=>n+chosen.length);toast.success(t('Saved to your memory.','Tersimpan di memorimu.'));}catch(e){setError(e instanceof Error?e.message:t('Nothing confirmed saved. Your review is still here.','Penyimpanan belum terkonfirmasi. Tinjauanmu tetap di sini.'));}finally{setSaving(false);}}
 return <div><PageHeader title={t('A little context. A clearer head.','Sedikit konteks. Pikiran lebih lega.')} subtitle={t('Add a conversation. Review what matters. Keep only what you need.','Tambahkan percakapan. Tinjau yang penting. Simpan yang kamu perlukan.')} />
 <form onSubmit={analyze} className="app-panel space-y-5"><div className="flex gap-2" role="group" aria-label={t('Input type','Jenis masukan')}>{(['text','image'] as const).map(m=><button type="button" key={m} aria-pressed={mode===m} className={mode===m?'n-button':'n-button secondary'} onClick={()=>{setMode(m);setResult(null);setDrafts([]);}}>{m==='text'?<FileText size={17}/>:<ImagePlus size={17}/>} {m==='text'?t('Paste text','Tempel teks'):'Screenshot'}</button>)}</div>
 {mode==='text'?<label className="n-field">{t('Conversation','Percakapan')}<textarea value={text} required maxLength={20000} rows={7} onChange={e=>setText(e.target.value)} placeholder={t('Paste a conversation with speaker names…','Tempel percakapan dengan nama pengirim…')}/></label>:<label className="n-field">{t('Screenshot (PNG, JPEG, WebP · max 5 MB)','Screenshot (PNG, JPEG, WebP · maks 5 MB)')}<input type="file" accept="image/png,image/jpeg,image/webp" required onChange={async e=>{const file=e.target.files?.[0];setImage('');if(!file)return;if(file.size>5_000_000){setError(t('Choose an image under 5 MB.','Pilih gambar di bawah 5 MB.'));e.target.value='';return;}const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.onerror=()=>setError(t('Could not read this file.','File tidak dapat dibaca.'));reader.readAsDataURL(file);}}/>{image&&<img src={image} className="max-h-64 w-auto rounded-xl object-contain" alt={t('Screenshot to review','Screenshot untuk ditinjau')}/>}</label>}
 <div className="grid gap-4 sm:grid-cols-2"><label className="n-field">{t('Your name in this chat','Namamu di percakapan ini')}<input value={me} maxLength={100} onChange={e=>setMe(e.target.value)} placeholder={t('Helps identify your promises','Untuk mengenali janjimu')}/></label><label className="n-field">{t('Chat or group name (optional)','Nama chat atau grup (opsional)')}<input value={source} maxLength={120} onChange={e=>setSource(e.target.value)}/></label><label className="n-field">{t('Original conversation date (optional)','Tanggal percakapan asli (opsional)')}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/><small>{t('Used to understand “tomorrow”. Leave blank if unknown.','Untuk memahami “besok”. Kosongkan jika tidak tahu.')}</small></label><label className="n-field">{t('Conversation time zone','Zona waktu percakapan')}<select value={timezone} onChange={e=>setTimezone(e.target.value as typeof timezone)}><option value="Asia/Jakarta">WIB · Asia/Jakarta</option><option value="Asia/Makassar">WITA · Asia/Makassar</option><option value="Asia/Jayapura">WIT · Asia/Jayapura</option></select></label></div>
 <p className="text-sm text-muted-foreground">{t('Only share content you have permission to use. Submitted text or screenshots are processed by our AI provider. Nothing is saved as a memory until you confirm.','Bagikan hanya konten yang boleh kamu gunakan. Teks atau screenshot diproses oleh penyedia AI kami. Memori baru disimpan setelah kamu konfirmasi.')}</p><button className="n-button" disabled={busy||saving||(mode==='image'&&!image)}>{busy?<Loader2 className="animate-spin" size={16}/>:null}{busy?t('Reading…','Membaca…'):t('Find what matters','Temukan yang penting')}</button>
 <p className="text-sm text-muted-foreground">{t('WhatsApp forwarding is not available yet.','Penerusan WhatsApp belum tersedia.')}</p></form>
 {error&&<p role="alert" className="my-5 rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}
 {result&&<section className="mt-8" aria-live="polite"><h2 className="text-xl font-semibold">{t('Your review','Tinjauanmu')}</h2><p className="my-3 text-muted-foreground">{result.summary}</p>{result.context.length>0&&<details className="mb-5"><summary>{t('Conversation context','Konteks percakapan')}</summary><ul className="list-disc pl-5">{result.context.map((c,n)=><li key={n}>{c}</li>)}</ul></details>}
 {!drafts.length&&!savedCount&&<p className="app-panel">{t('No clear commitments found. You can try another excerpt.','Tidak ada komitmen yang jelas. Kamu bisa mencoba potongan lain.')}</p>}
 <div className="space-y-4">{drafts.map((i,index)=><article key={i.id} className="app-panel space-y-4"><div className="flex items-center justify-between"><label className="flex items-center gap-2 font-medium"><input type="checkbox" checked={i.selected} onChange={e=>patch(i.id,{selected:e.target.checked})}/>{t('Memory','Memori')} {index+1}</label><button type="button" aria-label={t('Discard suggestion','Buang saran')} onClick={()=>setDrafts(s=>s.filter(d=>d.id!==i.id))}><X size={18}/></button></div><blockquote className="border-l-2 border-emerald-700 pl-4 text-sm leading-relaxed">“{i.quote}”</blockquote>{mode==='image'&&<p className="text-sm">{t('Check this quote against your screenshot.','Cocokkan kutipan ini dengan screenshot-mu.')}</p>}<label className="n-field">{t('What to remember','Yang perlu diingat')}<input value={i.title} maxLength={500} onChange={e=>patch(i.id,{title:e.target.value})}/></label><div className="grid gap-4 sm:grid-cols-2"><label className="n-field">{t('Who takes the next step?','Siapa yang bertindak?')}<select value={i.owner} onChange={e=>patch(i.id,{owner:e.target.value as Draft['owner']})}><option value="unknown">{t('Please choose','Pilih dulu')}</option><option value="me">{t('Me — my commitment','Saya — komitmen saya')}</option><option value="other">{t('Someone else — I’m waiting','Orang lain — saya menunggu')}</option></select></label><label className="n-field">{t('Date (optional)','Tanggal (opsional)')}<input type="date" value={i.whenParsed||''} onChange={e=>patch(i.id,{whenParsed:e.target.value||null,reminder:e.target.value?i.reminder:false})}/></label><label className="n-field">{t('Person (optional)','Orang (opsional)')}<input value={i.person||''} maxLength={200} onChange={e=>patch(i.id,{person:e.target.value||null})}/></label><label className="n-field">{t('Project (optional)','Proyek (opsional)')}<input value={i.project||''} maxLength={200} onChange={e=>patch(i.id,{project:e.target.value||null})}/></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" disabled={!i.whenParsed} checked={i.reminder} onChange={e=>patch(i.id,{reminder:e.target.checked})}/>{t('Show an in-app reminder on this date','Tampilkan pengingat di aplikasi pada tanggal ini')}</label><p className="text-sm text-muted-foreground">{i.aiNote}</p></article>)}</div>
 {drafts.length>0&&<div className="sticky bottom-20 mt-5 flex items-center justify-between gap-3 rounded-xl border bg-white p-4 shadow-sm lg:bottom-4"><span className="text-sm">{drafts.filter(i=>i.selected).length} {t('selected · no reminder unless chosen','dipilih · tanpa pengingat jika tidak diaktifkan')}</span><button className="n-button" onClick={save} disabled={saving||!drafts.some(i=>i.selected)}>{saving?<Loader2 size={16} className="animate-spin"/>:<Check size={16}/>} {saving?t('Saving…','Menyimpan…'):t('Save memories','Simpan memori')}</button></div>}
 {savedCount>0&&<p className="mt-5 flex items-center gap-3">{savedCount} {t('memories saved.','memori tersimpan.')}<Link to="/app/today" className="n-text-link">{t('Go to Today','Lihat Hari Ini')} <ArrowRight size={16}/></Link></p>}</section>}</div>;
}
