import { createFileRoute, Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowUp, Loader2, Sparkles } from 'lucide-react';
import { useLocale } from '@/lib/locale';
import { askAssistant } from '@/lib/nanti-ai.functions';
export const Route=createFileRoute('/app/')({head:()=>({meta:[{title:'Ask NANTI · Your memory'}]}),component:AskPage});
type Answer={question:string;answer:string;sources:{id:string;title:string;quote:string;source:string}[]};
function AskPage(){const {t,locale}=useLocale();const [question,setQuestion]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[answers,setAnswers]=useState<Answer[]>([]);
 async function ask(q:string){if(busy||!q.trim())return;setBusy(true);setError('');try{const r=await askAssistant({data:{question:q,language:locale}});setAnswers(s=>[...s,{question:q,...r}]);setQuestion('');}catch(e){setError(e instanceof Error?e.message:t('Please retry.','Silakan coba lagi.'));}finally{setBusy(false);}}
 const suggestions=[t('What did I promise?','Apa yang pernah saya janjikan?'),t('Who am I waiting for?','Saya sedang menunggu siapa?'),t('What needs my attention today?','Apa yang perlu saya perhatikan hari ini?')];
 return <div className="mx-auto max-w-2xl"><div className="py-12 text-center"><Sparkles className="mx-auto mb-4 text-primary" size={32}/><h1 className="text-3xl font-semibold">{t('Ask your memory.','Tanya memorimu.')}</h1><p className="mt-3 text-muted-foreground">{t('Find promises, people, and the conversation behind them.','Temukan janji, orang, dan percakapan di baliknya.')}</p></div><div className="space-y-6" aria-live="polite">{answers.map((a,n)=><article key={n}><p className="mb-4 ml-auto w-fit max-w-[90%] rounded-2xl bg-primary px-5 py-3 text-white">{a.question}</p><p className="whitespace-pre-wrap leading-relaxed">{a.answer}</p>{a.sources.length>0&&<details className="mt-3 rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">{t('Supporting memories','Memori sumber')} ({a.sources.length})</summary><div className="mt-3 space-y-4">{a.sources.map(s=><div key={s.id}><p className="font-medium">{s.title}</p><p className="text-sm text-muted-foreground">{s.source}</p><blockquote className="mt-1 border-l-2 pl-3 text-sm">{s.quote||t('No original quote saved.','Tidak ada kutipan asli tersimpan.')}</blockquote></div>)}</div></details>}</article>)}</div>
 <form className="app-panel sticky bottom-20 mt-7 lg:bottom-4" onSubmit={e=>{e.preventDefault();void ask(question);}}><label htmlFor="memory-question" className="sr-only">{t('Your question','Pertanyaanmu')}</label><div className="flex items-end gap-3"><textarea id="memory-question" className="min-h-16 w-full resize-y bg-transparent p-2 outline-offset-4" rows={2} maxLength={2000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder={t('What’s on your mind?','Apa yang ingin kamu ingat?')}/><button className="n-button" disabled={busy||!question.trim()} aria-label={t('Ask NANTI','Tanya NANTI')}>{busy?<Loader2 className="animate-spin" size={18}/>:<ArrowUp size={18}/>}</button></div>{error&&<p role="alert" className="mt-3 text-sm text-red-800">{error}</p>}</form>
 {!answers.length&&<div className="mt-4 flex flex-wrap justify-center gap-2">{suggestions.map(s=><button key={s} onClick={()=>ask(s)} disabled={busy} className="rounded-full border px-4 py-2 text-sm hover:bg-secondary">{s}</button>)}</div>}<p className="mt-5 text-center text-xs leading-relaxed text-muted-foreground">{t('Answers use recent saved memories and can be incomplete. Check the sources. Questions in this view are not saved.','Jawaban memakai memori tersimpan terbaru dan bisa tidak lengkap. Periksa sumbernya. Pertanyaan di tampilan ini tidak disimpan.')}</p><p className="mt-4 text-center"><Link to="/app/import" className="n-text-link">{t('Add a conversation','Tambahkan percakapan')}</Link></p></div>;
}
