import { createFileRoute, Link, useNavigate } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { PageHeader } from '@/components/nanti/app-shell';
import { useLocale, LanguageSwitch } from '@/lib/locale';
import { useNanti } from '@/lib/nanti-store';
import { useSupabaseAuth } from '@/hooks/use-supabase-auth';
import { getSubscription,startCheckout,exportAccount,deleteAccount } from '@/lib/launch.functions';
import { supabase } from '@/integrations/supabase/client';
export const Route=createFileRoute('/app/settings')({component:SettingsPage});
function SettingsPage(){const {t,locale}=useLocale();const {settings,setSettings}=useNanti();const {user,signOut}=useSupabaseAuth();const navigate=useNavigate();const [name,setName]=useState(settings.preferredName||settings.name),[busy,setBusy]=useState(''),[plan,setPlan]=useState<Awaited<ReturnType<typeof getSubscription>>|null>(null),[error,setError]=useState(''),[confirm,setConfirm]=useState(''),[password,setPassword]=useState(''),[deleting,setDeleting]=useState(false);
 async function refresh(){try{setPlan(await getSubscription());setError('');}catch{setError(t('Plan could not be loaded.','Paket belum dapat dimuat.'));}}useEffect(()=>{void refresh();},[]);
 async function action(key:string,fn:()=>Promise<void>){setBusy(key);setError('');try{await fn();}catch(e){setError(e instanceof Error?e.message:t('Please retry.','Silakan coba lagi.'));}finally{setBusy('');}}
 return <div className="space-y-7"><PageHeader title={t('Make yourself at home.','Buat NANTI terasa milikmu.')} subtitle={user?.email}/>{error&&<p className="rounded-xl bg-red-50 p-4 text-red-800" role="alert">{error}</p>}
 <section className="app-panel"><h2 className="mb-5 text-lg font-semibold">{t('Your profile','Profilmu')}</h2><form onSubmit={e=>{e.preventDefault();void action('profile',async()=>{await setSettings({name,preferredName:name,language:locale==='en'?'english':'indonesian'});toast.success(t('Profile saved.','Profil tersimpan.'));});}} className="space-y-4"><label className="n-field">{t('Preferred name','Nama panggilan')}<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} autoComplete="given-name"/></label><div className="flex items-center gap-4"><span className="text-sm">{t('Language','Bahasa')}</span><LanguageSwitch/></div><button className="n-button" disabled={!!busy}>{t('Save profile','Simpan profil')}</button></form></section>
 <section className="app-panel"><div className="flex items-start justify-between"><h2 className="text-lg font-semibold">NANTI Personal</h2><span className="rounded-full bg-secondary px-3 py-1 text-sm">{plan?plan.active?t('Active','Aktif'):t('Trial ended','Uji coba berakhir'):t('Loading','Memuat')}</span></div><p className="my-4 text-3xl font-semibold">Rp25.000 <span className="text-sm font-normal text-muted-foreground">/ {t('month','bulan')}</span></p><p className="text-sm leading-relaxed text-muted-foreground">{t('10 days free. No automatic charges. Each payment adds one month after your existing access ends. You can still read, export, or delete your memories after your trial.','Gratis 10 hari. Tanpa tagihan otomatis. Setiap pembayaran menambah satu bulan setelah akses yang ada berakhir. Kamu tetap bisa membaca, mengekspor, atau menghapus memori setelah uji coba.')}</p>{plan&&<p className="my-4 text-sm">{t('Access until','Akses sampai')} {new Intl.DateTimeFormat(locale==='en'?'en-GB':'id-ID',{dateStyle:'long'}).format(new Date(Math.max(Date.parse(plan.trial_ends_at),Date.parse(plan.paid_until||'1970-01-01'))))}</p>}
 <button disabled={!!busy||!plan?.paymentsEnabled} className="n-button mt-4" onClick={()=>action('payment',async()=>{const {url}=await startCheckout();window.location.assign(url);})}>{busy==='payment'?t('Opening checkout…','Membuka pembayaran…'):plan?.paymentsEnabled?t('Continue for Rp25.000','Lanjutkan Rp25.000'):t('Payments not available yet','Pembayaran belum tersedia')}</button><button onClick={refresh} className="ml-4 mt-3 text-sm underline">{t('Refresh payment status','Perbarui status pembayaran')}</button><p className="mt-4 text-xs text-muted-foreground">{t('GoPay and other methods depend on the options available at checkout. Access is confirmed after payment verification.','GoPay dan metode lain mengikuti pilihan yang tersedia saat pembayaran. Akses aktif setelah pembayaran diverifikasi.')}</p></section>
 <section className="app-panel"><h2 className="mb-4 text-lg font-semibold">{t('Connections','Koneksi')}</h2><div className="space-y-4">{['WhatsApp','Google Calendar',t('Push notifications','Notifikasi push')].map(label=><div key={label} className="flex justify-between gap-4 border-b pb-3 text-sm"><span>{label}</span><span className="text-muted-foreground">{t('Not available yet','Belum tersedia')}</span></div>)}</div><p className="mt-4 text-sm text-muted-foreground">{t('For now, paste text or upload a screenshot. Reminders appear inside NANTI.','Untuk saat ini, tempel teks atau unggah screenshot. Pengingat tampil di dalam NANTI.')}</p></section>
 <section className="app-panel"><h2 className="mb-4 text-lg font-semibold">{t('Your data, your choice','Datamu, pilihanmu')}</h2><button className="n-button secondary" disabled={!!busy} onClick={()=>action('export',async()=>{const data=await exportAccount();const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='nanti-memories.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);})}>{busy==='export'?t('Preparing export…','Menyiapkan ekspor…'):t('Download my data','Unduh data saya')}</button><p className="mt-4 text-sm"><Link to="/legal/privacy" className="underline">{t('Privacy policy','Kebijakan privasi')}</Link> · <Link to="/legal/terms" className="underline">{t('Terms','Ketentuan')}</Link> · <Link to="/contact" className="underline">{t('Contact','Hubungi kami')}</Link></p>
 <div className="mt-6 border-t pt-5">{!deleting?<button className="text-sm text-red-800 underline" onClick={()=>setDeleting(true)}>{t('Delete my account','Hapus akun saya')}</button>:<form className="space-y-4" onSubmit={e=>{e.preventDefault();void action('delete',async()=>{if(!user?.email)throw new Error('Please sign in again.');const {error:authError}=await supabase.auth.signInWithPassword({email:user.email,password});if(authError)throw new Error(t('Password verification failed.','Verifikasi kata sandi gagal.'));await deleteAccount({data:{confirmation:'DELETE'}});await signOut();await navigate({to:'/'});});}}><h3 className="font-semibold">{t('Permanently delete your account?','Hapus akun secara permanen?')}</h3><p className="text-sm text-muted-foreground">{t('This deletes your account and saved memories. Download an export first if you need it. This cannot be undone.','Akun dan memori tersimpan akan dihapus. Unduh salinan terlebih dahulu jika diperlukan. Tidak dapat dibatalkan.')}</p><label className="n-field">{t('Confirm your password','Konfirmasi kata sandi')}<input type="password" required value={password} autoComplete="current-password" onChange={e=>setPassword(e.target.value)}/></label><label className="n-field">{t('Type DELETE to confirm','Ketik DELETE untuk konfirmasi')}<input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/></label><div className="flex gap-3"><button type="button" className="n-button secondary" onClick={()=>setDeleting(false)}>{t('Keep my account','Pertahankan akun')}</button><button className="n-button !bg-red-800" disabled={confirm!=='DELETE'||!!busy}>{t('Delete permanently','Hapus permanen')}</button></div></form>}</div></section><button className="n-button secondary" onClick={()=>action('logout',async()=>{await signOut();await navigate({to:'/auth/login'});})}>{t('Sign out','Keluar')}</button></div>;
}
