import { createFileRoute, useNavigate } from '@tanstack/react-router';
import { useState,useEffect } from 'react';
import { Logo } from '@/components/nanti/logo';
import { LanguageSwitch,useLocale } from '@/lib/locale';
import { useNanti } from '@/lib/nanti-store';
import { useSupabaseAuth } from '@/hooks/use-supabase-auth';
export const Route=createFileRoute('/welcome')({component:Welcome});
function Welcome(){const {t,locale}=useLocale();const {user,loading}=useSupabaseAuth();const {settings,setSettings,hydrated,error,reload}=useNanti();const [name,setName]=useState(''),[busy,setBusy]=useState(false);const navigate=useNavigate();useEffect(()=>{if(!loading&&!user)void navigate({to:'/auth/login'});else if(hydrated&&settings.onboarded)void navigate({to:'/app/today'});},[loading,user,hydrated,settings.onboarded,navigate]);
 if(loading||!hydrated||!user)return <p role="status" className="p-12">{t('Loading…','Memuat…')}</p>;
 return <main className="mx-auto flex min-h-screen max-w-lg flex-col justify-center gap-7 px-6 py-16"><div className="flex items-center justify-between"><Logo/><LanguageSwitch/></div><h1 className="text-3xl font-semibold">{t('A place for your “later.”','Tempat untuk semua “nanti”.')}</h1><p className="text-muted-foreground">{t('Start with one conversation. NANTI will help you find promises and things you are waiting for, then let you review them.','Mulai dari satu percakapan. NANTI membantu menemukan janji dan hal yang kamu tunggu, lalu memberimu kesempatan untuk meninjaunya.')}</p>{error?<div role="alert"><p>{error}</p><button className="n-button" onClick={reload}>{t('Retry','Coba lagi')}</button></div>:<form className="space-y-5" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await setSettings({name,preferredName:name,onboarded:true,language:locale==='en'?'english':'indonesian',reminderChannels:['in_app']});await navigate({to:'/app/import'});}catch{/* store displays failure */}finally{setBusy(false);}}}><label className="n-field">{t('What should we call you?','Kami panggil kamu siapa?')}<input required maxLength={100} autoComplete="given-name" value={name} onChange={e=>setName(e.target.value)}/></label><button className="n-button w-full" disabled={busy}>{busy?t('Saving…','Menyimpan…'):t('Add my first conversation','Tambahkan percakapan pertamaku')}</button></form>}<p className="text-sm text-muted-foreground">{t('Your 10-day trial starts when you first open your workspace. No card required.','Uji coba 10 hari dimulai saat pertama membuka ruang kerja. Tanpa kartu pembayaran.')}</p></main>;
}
