import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowRight, Check, Plus, Search, Bell, Undo2, Trash2 } from 'lucide-react';
import { useNanti } from '@/lib/nanti-store';
import { useLocale } from '@/lib/locale';
import type { Item } from '@/lib/nanti-types';
import { PageHeader } from './app-shell';
import { todayISO } from '@/lib/nanti-utils';
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
export function MemoryCard({item}:{item:Item}){const {t}=useLocale();const {update,complete,remove,busy,personOf,projectOf}=useNanti();const [editing,setEditing]=useState(false),[title,setTitle]=useState(item.title),[due,setDue]=useState(item.due||''),[reminder,setReminder]=useState(!!item.reminderEnabled),[confirmDelete,setConfirmDelete]=useState(false);const closed=item.status==='done'||item.status==='received'||item.status==='ignored';
 return <article className="app-panel"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><p className="mb-2 text-xs font-medium uppercase tracking-wider text-primary">{closed?t('Completed or archived','Selesai atau diarsipkan'):item.kind==='waiting'?t('Waiting for someone','Menunggu orang lain'):t('My commitment','Komitmen saya')}</p><h3 className="text-base font-semibold">{item.title}</h3><p className="mt-2 text-sm text-muted-foreground">{[item.personName||personOf(item.personId)?.name,item.projectName||projectOf(item.projectId)?.name,item.due].filter(Boolean).join(' · ')||t('No date set','Tanpa tanggal')}</p></div><button disabled={busy} onClick={()=>closed?update(item.id,{status:'open'}):complete(item.id)} className="rounded-full border p-3 hover:bg-secondary" aria-label={closed?t('Reopen memory','Buka kembali memori'):item.kind==='waiting'?t('Mark received','Tandai diterima'):t('Mark complete','Tandai selesai')}>{closed?<Undo2 size={17}/>:<Check size={17}/>}</button></div>
 <details className="mt-4 text-sm"><summary className="cursor-pointer text-muted-foreground">{t('Source & details','Sumber & detail')}</summary><p className="mt-3 font-medium">{item.source}</p><blockquote className="my-3 whitespace-pre-wrap border-l-2 border-primary/30 pl-3">{item.quote||t('No original quote saved.','Kutipan asli tidak tersimpan.')}</blockquote>{item.aiNote&&<p className="text-muted-foreground">{item.aiNote}</p>}<div className="mt-4 flex gap-4"><button onClick={()=>{setTitle(item.title);setDue(item.due||'');setReminder(!!item.reminderEnabled);setEditing(!editing);}} className="n-text-link">{t('Edit memory','Edit memori')}</button><button className="text-red-800" onClick={()=>setConfirmDelete(true)}>{t('Delete','Hapus')}</button></div></details>
 {editing&&<form className="mt-5 space-y-4 border-t pt-5" onSubmit={async e=>{e.preventDefault();await update(item.id,{title,due:due||undefined,time:undefined,reminderEnabled:reminder&&!!due});setEditing(false);}}><label className="n-field">{t('Memory','Memori')}<input required maxLength={500} value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="n-field">{t('Date (optional)','Tanggal (opsional)')}<input type="date" value={due} onChange={e=>{setDue(e.target.value);if(!e.target.value)setReminder(false);}}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={reminder} disabled={!due} onChange={e=>setReminder(e.target.checked)}/>{t('Show in-app reminder','Tampilkan pengingat di aplikasi')}</label><button disabled={busy} className="n-button">{t('Save changes','Simpan perubahan')}</button></form>}
 {item.reminderEnabled&&!closed&&<p className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><Bell size={13}/>{t('In-app reminder','Pengingat di aplikasi')}</p>}
 <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('Delete this memory?','Hapus memori ini?')}</AlertDialogTitle><AlertDialogDescription>{t('This removes the memory and its saved quote. It cannot be undone.','Memori dan kutipan tersimpannya akan dihapus. Tidak dapat dibatalkan.')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t('Keep memory','Simpan memori')}</AlertDialogCancel><AlertDialogAction onClick={()=>void remove(item.id)}>{t('Delete','Hapus')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></article>;
}
export function MemoryCollection({view}:{view:'today'|'all'|'waiting'|'reminders'|'followups'}){const {t,locale}=useLocale();const {items,settings}=useNanti();const [query,setQuery]=useState(''),[filter,setFilter]=useState<'open'|'closed'>('open');const today=todayISO();const open=items.filter(i=>i.status==='open'||i.status==='inbox');const due=open.filter(i=>i.due&&i.due<=today);const waiting=open.filter(i=>i.kind==='waiting');const visible=items.filter(i=>filter==='open'?i.status==='open'||i.status==='inbox':i.status==='done'||i.status==='received'||i.status==='ignored').filter(i=>view==='waiting'||view==='followups'?i.kind==='waiting'||i.kind==='followup':view==='reminders'?i.reminderEnabled:true).filter(i=>`${i.title} ${i.personName||''} ${i.projectName||''} ${i.quote}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));
 const title=view==='today'?t(`Hello${settings.name?', '+settings.name:''}.`,`Halo${settings.name?', '+settings.name:''}.`):view==='all'?t('Your memory','Memorimu'):view==='waiting'?t('Waiting, with context.','Menunggu, dengan konteks.'):view==='followups'?t('Ready for a follow-up?','Saatnya menindaklanjuti?'):t('Your reminders','Pengingatmu');
 return <div>{view==='today'&&<p className="mb-3 text-sm text-muted-foreground">{new Intl.DateTimeFormat(locale==='en'?'en-GB':'id-ID',{dateStyle:'full'}).format(new Date())}</p>}<PageHeader title={title} subtitle={view==='reminders'?t('Shown while you use NANTI. WhatsApp and push delivery are not available yet.','Ditampilkan saat kamu menggunakan NANTI. Pengiriman WhatsApp dan push belum tersedia.'):t('Keep the promise. Keep the conversation behind it.','Ingat janjinya. Simpan percakapan di baliknya.')} action={<Link className="n-button" to="/app/import"><Plus size={17}/><span className="hidden sm:inline">{t('Add memory','Tambah memori')}</span></Link>}/>
 {view==='today'&&<><div className="mb-8 grid grid-cols-3 gap-3">{[[due.length,t('Due or overdue','Jatuh tempo')],[waiting.length,t('Waiting','Menunggu')],[open.length,t('Open memories','Memori terbuka')]].map(([n,label])=><div key={label} className="rounded-2xl border bg-[#f8faf7] p-4"><p className="text-3xl font-semibold">{n}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div>{due.length>0&&<section className="mb-8"><h2 className="mb-4 text-lg font-semibold">{t('Worth your attention','Perlu perhatianmu')}</h2><div className="space-y-3">{due.map(i=><MemoryCard key={i.id} item={i}/>)}</div></section>}<p className="mb-4 text-sm text-muted-foreground">{t('A saved due date is a reminder to review—not proof that something is unfinished. Mark it complete when you know.','Tanggal yang tersimpan mengingatkanmu untuk meninjau. Tandai selesai jika kamu sudah memastikannya.')}</p></>}
 <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-xl bg-secondary p-1">{(['open','closed'] as const).map(f=><button key={f} aria-pressed={filter===f} className={`rounded-lg px-4 py-2 text-sm ${filter===f?'bg-white shadow-sm':''}`} onClick={()=>setFilter(f)}>{f==='open'?t('Open','Terbuka'):t('Completed & archived','Selesai & arsip')}</button>)}</div><label className="flex items-center gap-2 rounded-xl border px-3"><Search size={16}/><input className="min-w-0 bg-transparent py-2 text-sm" aria-label={t('Search memories','Cari memori')} placeholder={t('Search your memory…','Cari di memorimu…')} value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {visible.length?<div className="space-y-3">{visible.filter(i=>view!=='today'||!due.some(d=>d.id===i.id)||filter==='closed').map(i=><MemoryCard key={i.id} item={i}/>)}</div>:<div className="app-panel py-12 text-center"><h2 className="text-lg font-medium">{query?t('No matching memories','Tidak ada memori yang cocok'):items.length?t('Nothing here for now','Belum ada di sini'):t('Your next “nanti” starts here.','“Nanti” berikutnya mulai di sini.')}</h2><p className="mx-auto mt-3 max-w-md text-sm text-muted-foreground">{t('Add a conversation, review the suggestions, and save what matters to you.','Tambahkan percakapan, tinjau sarannya, lalu simpan yang penting bagimu.')}</p><Link to="/app/import" className="n-text-link mt-5 inline-flex items-center gap-2">{t('Add a conversation','Tambahkan percakapan')}<ArrowRight size={16}/></Link></div>}</div>;
}
