/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppFollowUpsRouteImport } from './routes/app.follow-ups'
import { Route as AppImportRouteImport } from './routes/app.import'
import { Route as AppInboxRouteImport } from './routes/app.inbox'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppPeopleRouteImport } from './routes/app.people'
import { Route as AppRemindersRouteImport } from './routes/app.reminders'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTodayRouteImport } from './routes/app.today'
import { Route as AppWaitingRouteImport } from './routes/app.waiting'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiCronCheckRemindersRouteImport } from './routes/api/cron/check-reminders'
import { Route as ApiCronSyncCalendarRouteImport } from './routes/api/cron/sync-calendar'
import { Route as ApiInvoicesPdfRouteImport } from './routes/api/invoices/pdf'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPushUnsubscribeRouteImport } from './routes/api/push/unsubscribe'
import { Route as ApiRemindersCompleteRouteImport } from './routes/api/reminders/complete'
import { Route as ApiRemindersSnoozeRouteImport } from './routes/api/reminders/snooze'
import { Route as ApiWebhooksWhatsappRouteImport } from './routes/api/webhooks/whatsapp'
import { Route as AppProjectsIndexRouteImport } from './routes/app.projects.index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/app.projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppPeopleRoute = AppPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppWaitingRoute = AppWaitingRouteImport.update({
  id: '/waiting',
  path: '/waiting',
  getParentRoute: () => AppRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronCheckRemindersRoute = ApiCronCheckRemindersRouteImport.update({
  id: '/api/cron/check-reminders',
  path: '/api/cron/check-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncCalendarRoute = ApiCronSyncCalendarRouteImport.update({
  id: '/api/cron/sync-calendar',
  path: '/api/cron/sync-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInvoicesPdfRoute = ApiInvoicesPdfRouteImport.update({
  id: '/api/invoices/pdf',
  path: '/api/invoices/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
  id: '/api/push/unsubscribe',
  path: '/api/push/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindersCompleteRoute = ApiRemindersCompleteRouteImport.update({
  id: '/api/reminders/complete',
  path: '/api/reminders/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindersSnoozeRoute = ApiRemindersSnoozeRouteImport.update({
  id: '/api/reminders/snooze',
  path: '/api/reminders/snooze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappRoute = ApiWebhooksWhatsappRouteImport.update({
  id: '/api/webhooks/whatsapp',
  path: '/api/webhooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/business': typeof BusinessRoute
  '/careers': typeof CareersRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/personal': typeof PersonalRoute
  '/pricing': typeof PricingRoute
  '/welcome': typeof WelcomeRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/import': typeof AppImportRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/people': typeof AppPeopleRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/waiting': typeof AppWaitingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/cron/check-reminders': typeof ApiCronCheckRemindersRoute
  '/api/cron/sync-calendar': typeof ApiCronSyncCalendarRoute
  '/api/invoices/pdf': typeof ApiInvoicesPdfRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/reminders/complete': typeof ApiRemindersCompleteRoute
  '/api/reminders/snooze': typeof ApiRemindersSnoozeRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/business': typeof BusinessRoute
  '/careers': typeof CareersRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/personal': typeof PersonalRoute
  '/pricing': typeof PricingRoute
  '/welcome': typeof WelcomeRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/import': typeof AppImportRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/people': typeof AppPeopleRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/waiting': typeof AppWaitingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app': typeof AppIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/cron/check-reminders': typeof ApiCronCheckRemindersRoute
  '/api/cron/sync-calendar': typeof ApiCronSyncCalendarRoute
  '/api/invoices/pdf': typeof ApiInvoicesPdfRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/reminders/complete': typeof ApiRemindersCompleteRoute
  '/api/reminders/snooze': typeof ApiRemindersSnoozeRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects': typeof AppProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/affiliates': typeof AffiliatesRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/business': typeof BusinessRoute
  '/careers': typeof CareersRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/personal': typeof PersonalRoute
  '/pricing': typeof PricingRoute
  '/welcome': typeof WelcomeRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/import': typeof AppImportRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/people': typeof AppPeopleRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/today': typeof AppTodayRoute
  '/app/waiting': typeof AppWaitingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/google': typeof ApiAuthGoogleRoute
  '/api/cron/check-reminders': typeof ApiCronCheckRemindersRoute
  '/api/cron/sync-calendar': typeof ApiCronSyncCalendarRoute
  '/api/invoices/pdf': typeof ApiInvoicesPdfRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/reminders/complete': typeof ApiRemindersCompleteRoute
  '/api/reminders/snooze': typeof ApiRemindersSnoozeRoute
  '/api/webhooks/whatsapp': typeof ApiWebhooksWhatsappRoute
  '/app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/app/projects/': typeof AppProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliates'
    | '/app'
    | '/auth'
    | '/blog'
    | '/business'
    | '/careers'
    | '/help'
    | '/how-it-works'
    | '/personal'
    | '/pricing'
    | '/welcome'
    | '/app/follow-ups'
    | '/app/import'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/people'
    | '/app/reminders'
    | '/app/settings'
    | '/app/today'
    | '/app/waiting'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/api/auth/google'
    | '/api/cron/check-reminders'
    | '/api/cron/sync-calendar'
    | '/api/invoices/pdf'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/reminders/complete'
    | '/api/reminders/snooze'
    | '/api/webhooks/whatsapp'
    | '/app/projects/$projectId'
    | '/app/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/affiliates'
    | '/auth'
    | '/blog'
    | '/business'
    | '/careers'
    | '/help'
    | '/how-it-works'
    | '/personal'
    | '/pricing'
    | '/welcome'
    | '/app/follow-ups'
    | '/app/import'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/people'
    | '/app/reminders'
    | '/app/settings'
    | '/app/today'
    | '/app/waiting'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app'
    | '/api/auth/google'
    | '/api/cron/check-reminders'
    | '/api/cron/sync-calendar'
    | '/api/invoices/pdf'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/reminders/complete'
    | '/api/reminders/snooze'
    | '/api/webhooks/whatsapp'
    | '/app/projects/$projectId'
    | '/app/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/affiliates'
    | '/app'
    | '/auth'
    | '/blog'
    | '/business'
    | '/careers'
    | '/help'
    | '/how-it-works'
    | '/personal'
    | '/pricing'
    | '/welcome'
    | '/app/follow-ups'
    | '/app/import'
    | '/app/inbox'
    | '/app/invoices'
    | '/app/people'
    | '/app/reminders'
    | '/app/settings'
    | '/app/today'
    | '/app/waiting'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/api/auth/google'
    | '/api/cron/check-reminders'
    | '/api/cron/sync-calendar'
    | '/api/invoices/pdf'
    | '/api/push/subscribe'
    | '/api/push/unsubscribe'
    | '/api/reminders/complete'
    | '/api/reminders/snooze'
    | '/api/webhooks/whatsapp'
    | '/app/projects/$projectId'
    | '/app/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  BusinessRoute: typeof BusinessRoute
  CareersRoute: typeof CareersRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PersonalRoute: typeof PersonalRoute
  PricingRoute: typeof PricingRoute
  WelcomeRoute: typeof WelcomeRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRoute
  ApiCronCheckRemindersRoute: typeof ApiCronCheckRemindersRoute
  ApiCronSyncCalendarRoute: typeof ApiCronSyncCalendarRoute
  ApiInvoicesPdfRoute: typeof ApiInvoicesPdfRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute
  ApiRemindersCompleteRoute: typeof ApiRemindersCompleteRoute
  ApiRemindersSnoozeRoute: typeof ApiRemindersSnoozeRoute
  ApiWebhooksWhatsappRoute: typeof ApiWebhooksWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/follow-ups': {
      id: '/app/follow-ups'
      path: '/follow-ups'
      fullPath: '/app/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import': {
      id: '/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/people': {
      id: '/app/people'
      path: '/people'
      fullPath: '/app/people'
      preLoaderRoute: typeof AppPeopleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/waiting': {
      id: '/app/waiting'
      path: '/waiting'
      fullPath: '/app/waiting'
      preLoaderRoute: typeof AppWaitingRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/check-reminders': {
      id: '/api/cron/check-reminders'
      path: '/api/cron/check-reminders'
      fullPath: '/api/cron/check-reminders'
      preLoaderRoute: typeof ApiCronCheckRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-calendar': {
      id: '/api/cron/sync-calendar'
      path: '/api/cron/sync-calendar'
      fullPath: '/api/cron/sync-calendar'
      preLoaderRoute: typeof ApiCronSyncCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invoices/pdf': {
      id: '/api/invoices/pdf'
      path: '/api/invoices/pdf'
      fullPath: '/api/invoices/pdf'
      preLoaderRoute: typeof ApiInvoicesPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/unsubscribe': {
      id: '/api/push/unsubscribe'
      path: '/api/push/unsubscribe'
      fullPath: '/api/push/unsubscribe'
      preLoaderRoute: typeof ApiPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders/complete': {
      id: '/api/reminders/complete'
      path: '/api/reminders/complete'
      fullPath: '/api/reminders/complete'
      preLoaderRoute: typeof ApiRemindersCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders/snooze': {
      id: '/api/reminders/snooze'
      path: '/api/reminders/snooze'
      fullPath: '/api/reminders/snooze'
      preLoaderRoute: typeof ApiRemindersSnoozeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp': {
      id: '/api/webhooks/whatsapp'
      path: '/api/webhooks/whatsapp'
      fullPath: '/api/webhooks/whatsapp'
      preLoaderRoute: typeof ApiWebhooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/projects/': {
      id: '/app/projects/'
      path: '/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects/$projectId': {
      id: '/app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppImportRoute: typeof AppImportRoute
  AppInboxRoute: typeof AppInboxRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPeopleRoute: typeof AppPeopleRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppWaitingRoute: typeof AppWaitingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppImportRoute: AppImportRoute,
  AppInboxRoute: AppInboxRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPeopleRoute: AppPeopleRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodayRoute: AppTodayRoute,
  AppWaitingRoute: AppWaitingRoute,
  AppIndexRoute: AppIndexRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AffiliatesRoute: AffiliatesRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  BusinessRoute: BusinessRoute,
  CareersRoute: CareersRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  PersonalRoute: PersonalRoute,
  PricingRoute: PricingRoute,
  WelcomeRoute: WelcomeRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRoute,
  ApiCronCheckRemindersRoute: ApiCronCheckRemindersRoute,
  ApiCronSyncCalendarRoute: ApiCronSyncCalendarRoute,
  ApiInvoicesPdfRoute: ApiInvoicesPdfRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
  ApiRemindersCompleteRoute: ApiRemindersCompleteRoute,
  ApiRemindersSnoozeRoute: ApiRemindersSnoozeRoute,
  ApiWebhooksWhatsappRoute: ApiWebhooksWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
