alter policy "select_own_projects" on public.projects using ((select auth.uid()) = user_id);
alter policy "insert_own_projects" on public.projects with check ((select auth.uid()) = user_id);
alter policy "update_own_projects" on public.projects using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "delete_own_projects" on public.projects using ((select auth.uid()) = user_id);
alter policy "select_own_people" on public.people using ((select auth.uid()) = user_id);
alter policy "insert_own_people" on public.people with check ((select auth.uid()) = user_id);
alter policy "update_own_people" on public.people using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "delete_own_people" on public.people using ((select auth.uid()) = user_id);
alter policy "select_own_conversations" on public.conversations using ((select auth.uid()) = user_id);
alter policy "insert_own_conversations" on public.conversations with check ((select auth.uid()) = user_id);
alter policy "update_own_conversations" on public.conversations using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "delete_own_conversations" on public.conversations using ((select auth.uid()) = user_id);
alter policy "select_own_tasks" on public.tasks using ((select auth.uid()) = user_id);
alter policy "insert_own_tasks" on public.tasks with check ((select auth.uid()) = user_id);
alter policy "update_own_tasks" on public.tasks using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "delete_own_tasks" on public.tasks using ((select auth.uid()) = user_id);
alter policy "select_own_waiting" on public.waiting_items using ((select auth.uid()) = user_id);
alter policy "insert_own_waiting" on public.waiting_items with check ((select auth.uid()) = user_id);
alter policy "update_own_waiting" on public.waiting_items using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "delete_own_waiting" on public.waiting_items using ((select auth.uid()) = user_id);
alter policy "select_own_ai_messages" on public.ai_messages using ((select auth.uid()) = user_id);
alter policy "insert_own_ai_messages" on public.ai_messages with check ((select auth.uid()) = user_id);
alter policy "update_own_ai_messages" on public.ai_messages using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "delete_own_ai_messages" on public.ai_messages using ((select auth.uid()) = user_id);
alter policy "select_own_inbox" on public.inbox_items using ((select auth.uid()) = user_id);
alter policy "insert_own_inbox" on public.inbox_items with check ((select auth.uid()) = user_id);
alter policy "update_own_inbox" on public.inbox_items using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "delete_own_inbox" on public.inbox_items using ((select auth.uid()) = user_id);
alter policy "select_own_whatsapp_config" on public.whatsapp_configs using ((select auth.uid()) = user_id);
alter policy "insert_own_whatsapp_config" on public.whatsapp_configs with check ((select auth.uid()) = user_id);
alter policy "update_own_whatsapp_config" on public.whatsapp_configs using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
alter policy "delete_own_whatsapp_config" on public.whatsapp_configs using ((select auth.uid()) = user_id);
